name: Deploy via ftp
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with: 
          server: ftp.homebuddy.ro
          username: github@homebuddy.ro
          password: ${{ secrets.ftp_password }}
